apiVersion: v2
name: crewai-agent-4
description: Deploys a crewai agent using the standard Node.js Chart
version: 0.1.0
dependencies:
  - name: crewai-on-openshift
    version: 0.1.0
    repository: https://rhdh-demo-gh.github.io/helm-charts/