crewai-on-openshift:
  image:
    repository: ghcr.io/rhdh-demo-gh/{{ .Values.name }}
    pullPolicy: IfNotPresent
    tag: "main"

  # Disable health and readiness probes
  livenessProbe: null
  readinessProbe: null
