crewai-on-openshift:
  name: crewai-fastapi  # Define an app name
  image:
    repository: ghcr.io/rhdh-demo-gh/{{ .Values.name }}
    pullPolicy: IfNotPresent
    tag: "main"

  # Service Configuration
  service:
    type: ClusterIP  # Keep internal, OpenShift Route will expose it
    port: 80
    targetPort: 8000  # Your FastAPI app listens on this port

  # Enable OpenShift Route (instead of Ingress)
  route:
    enabled: true
    host: "your-app.apps.your-cluster.com"  # Update this with your OpenShift cluster

  # Security Context (Required for OpenShift)
  securityContext:
    runAsUser: 1001  # Ensure non-root execution
    allowPrivilegeEscalation: false

  # Resource Requests/Limits (Optional, but recommended)
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"

  # Disable health probes if FastAPI doesn’t support them
  livenessProbe: null
  readinessProbe: null

